version: '3.9'
services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      TZ: Europe/Kiev
    ports:
      - "$PG_PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9.22.3-alpine
    command:
      - "-url=jdbc:postgresql://postgres:5432/$PG_DB"
      - "-user=$PG_USER"
      - "-password=$PG_PASSWORD"
      - "migrate"
    depends_on:
      - postgres
    volumes:
      - ./.migration:/flyway/sql

  node:
    image: node:lts-alpine3.18
    user: $CURRENT_UID:$CURRENT_GID
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app

  dev:
    extends:
      service: node
    command: yarn dev
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:5173

  prod:
    extends:
      service: node
    command: yarn prod
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:3000

volumes:
  postgres_data:
